### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by b1ek** [WilliamHYZhang/Reddit-Bot-Account-Maker#2]
So people can just do
```
pip install -r requirements.txt
```
Instead of copying and pasting all those modules from README to cmd

requirements.txt:
```
selenium
tor
requests
names
```

**Comment by SloppyPuppy** [comment]
Yea, Im a newbie, and that would be useful, also I fixed the email service request but idk how to push this change so if you do here's the change:
`61> email = emailDriver.find_element_by_xpath('/html/body/div/div/div/div/div[2]/div/div[1]/div/div/p/span[1]/a/button').text`
Also, its quite obvious that we are necroing this dead project because of /r/place :)

**Comment by WilliamHYZhang** [comment]
Completed in #3

**Comment by WilliamHYZhang** [comment]
Completed in #3
